name: Déploiement FTP automatisé

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Déploiement chez LWS via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./public
          server-dir: /www/
          delete: true
